import { GetServerSideProps } from "next";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";

const StrapiLocalization = () => {
  const { t } = useTranslation(undefined, {
    keyPrefix: "AboutUs",
  });

  return (
    <>
      <Head>
        <title>Strapi Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{t("atAGlance.note")}</h1>
        <h3>{t("atAGlance.title")}</h3>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  return {
    props: {
      ...(await serverSideTranslations(ctx.locale!, ["common"])),
      // Will be passed to the page component as props
    },
  };
};

export default StrapiLocalization;
