import { useTranslation } from "@/hooks/useTranslation";
import { GetServerSideProps } from "next";
import Head from "next/head";

const StrapiLocalization = () => {
  const { t } = useTranslation("AboutUs.atAGlance", {
    variables: {
      date: "23.02.2023",
    },
  });

  return (
    <>
      <Head>
        <title>Strapi Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{t("note")}</h1>
        <h3>{t("title")}</h3>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  return {
    props: {},
  };
};

export default StrapiLocalization;
